### ISSUE TITLE
v0.3.3 - Improved Categories

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Mobile#104]
### Improved Categories

- N/A

### Miscellaneous

- [x] #106 - DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.
- [x] #107 - Hide the floating toolbar when hiding the player.
- [x] #108 - The score grid is not scrollable
- [x] #109 - Stack notifications at the bottom of the screen

### Compare

https://github.com/kidoju/Kidoju-Mobile/compare/v0.3.2...v0.3.3
