### ISSUE TITLE
v0.3.5 - Release Kendo-Mobile for app store approval (before public release)

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Mobile#114]
### Release Kendo-Mobile for app store approval (before public release) 

- [x] #43 - Get SafariViewController (Chrome Custom Tabs) to work on Android
- [x] #52 - Display last user score on #summary view
- [x] #58 - Merge settings (especially language and theme) with user profile
- [x] #59 - Test QR scan errors and show relevant message
- [x] #62 - Review all themes before release
- [x] #67 - TTS stops in Google Chrome on Windows after a certain number of characters
- [x] #75 - Filter by organization, author, category, ... for white label version of app
- [x] #79 - Factorize common code in init and show event handlers
- [x] #82 - Keep categories if they cannot be updated, e.g. no internet connection (avoid blank screen)
- [x] #85 - Add author, publication date and metrics to summary view
- [x] #86 - Compare internal version with ping version and require an update when necessary
- [x] #90 - Add activities graph
- [x] #98 - Configure google analytics
- [x] #111 - Do not display the floating toolbar in correction mode
- [x] #118 - Hiding iOS StatusBar does not work with Phonegap 7.0.1 and PGB Build v2
- [x] #119 - com.android.dex.DexException: Multiple dex files define Lorg/apache/cordova/BuildHelper
- [x] #120 - Install and configure android to build locally
- [x] #121 - Remove ghost callout when swiping over instructions and explanations on iOS
- [x] #122 - Swiping through #player and#correction pages gets stuck on iOS
- [x] #123 - Regression: phonegap-plugin-barcodescanner v7.0.0 does not load on android
- [x] #125 - Monitor battery status and warn
- [x] #126 - Switching views should reset view scrollers
- [x] #127 - Changing views should close actions sheets and drop down lists
- [x] #128 - Check display of answers and solutions in #score view for all tools
- [x] #129 - Opening and navigating the drawer while no network prevents url redirection
- [x] #130 - Changing theme does not work
- [x] #133 - Show summaries which have been scored in the #finder and #summary views
- [x] #134 - Localize "Search..." placeholder and "Press to load more" button
- [x] #136 - Remove cordova-plugin-compat
- [x] #137 - Add local notifications
- [x] #138 - Swipe to change users
- [x] #139 - Consider embedding all O Collection icons
- [x] #142 - Phonegap build fails for android since upgrading cordova-plugin-file-transfer to v1.7.0
- [x] #147 - Fix disappearing tags when scrolling the #finder
- [x] #148 - Cancel TTS speak when navigating pages in #player and #correction
- [x] #149 - On Android, opening the keyboard resizes the view
- [x] #150 - Fix queries when running on CELL connection
- [x] #152 - Uncaught TypeError: Cannot read property 'view' of undefined
- [x] #153 - Offline searches do not work on mobile devices
- [x] #155 - Prevent the showScoreInfo and clickSubmitInfo notifications to appear repeatedly
- [x] #156 - Missing pages in #activity scores
- [x] #158 - Disappearing user picture
- [x] #159 - Transition off of cordova-plugin-file-transfer
- [x] #165 - Signin buttons poorly aligned since added to scrollview with onboarding
- [x] #166 - Allow to change PIN
- [x] #169 - Add application rating on app stores
- [x] #170 - Reposition badges to the right in themes with list anchors without > icon
- [x] #171 - Review quiz buttons and select colors
- [x] #172 - Dropdown does not show popup on #categories with android dark and light themes
- [x] #173 - Activities not recorded outside development environment
- [x] #174 - Activities not reloaded when switching between users
- [x] #175 - Dig deeper into configuring android launchMode
- [x] #176 - Remove cordova-plugin-globalization
- [x] #177 - Android app restarts upon changing screen orientation
- [x] #181 - Error triggered when clicking back button on Android (and in the browser)

### Miscellaneous

- N/A

### Compare

https://github.com/kidoju/Kidoju-Mobile/compare/v0.3.4...v0.3.5
