### ISSUE TITLE
v0.3.6 - Add VectorDrawing to Kidoju-WebApp

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Mobile#115]
### Add VectorDrawing to Kidoju-WebApp

- N/A

### Miscellaneous

- [x] #57 - Sync activities with server
- [x] #80 - Consider a quick tour
- [x] #154 - Remove lower-casing discriminator type to match Kidoju-Server in various code locations
- [x] #163 - Add date and app.constants.appScheme to activities
- [x] #182 - Add current user to drawer
- [x] #187 - Progress app stores compliance and review
- [x] #188 - Refused to connect to 'https://graph.facebook.com/v2.8/786640958186206/picture' because it violates the document's Content Security Policy.
- [x] #189 - String.prototype.startsWith is missing on some Android platforms

### Compare

https://github.com/kidoju/Kidoju-Mobile/compare/v0.3.5...v0.3.6
